language: java
sudo: false

jdk:
  - oraclejdk7

os:
  - linux

env:
  global:
    - REPO="rjnienaber/quorum-ci"
    - CI_HOME=`pwd`/$REPO

script: cd $CI_HOME/Quorum3 && ./build.sh

notifications:
  email: false

branches:
  only:
    - master