language: java
sudo: false

jdk:
  - oraclejdk7

os:
  - linux

env:
  global:
    - CI_HOME=`pwd`

script: cd $CI_HOME/Quorum3 && ./build.sh

notifications:
  email: false

branches:
  only:
    - master